/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperacoesRouteImport } from './routes/_authenticated/operacoes'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedAjustesIndexRouteImport } from './routes/_authenticated/ajustes.index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedAjustesPlanosRouteImport } from './routes/_authenticated/ajustes.planos'
import { Route as AuthenticatedAjustesPerfilRouteImport } from './routes/_authenticated/ajustes.perfil'
import { Route as AuthenticatedAjustesOnboardingRouteImport } from './routes/_authenticated/ajustes.onboarding'
import { Route as AuthenticatedAjustesIntegracoesRouteImport } from './routes/_authenticated/ajustes.integracoes'
import { Route as AuthenticatedAjustesEquipeRouteImport } from './routes/_authenticated/ajustes.equipe'
import { Route as AuthenticatedAjustesComissaoRouteImport } from './routes/_authenticated/ajustes.comissao'
import { Route as AuthenticatedAjustesCargosRouteImport } from './routes/_authenticated/ajustes.cargos'
import { Route as ApiPublicHooksSyncAdsRouteImport } from './routes/api/public/hooks/sync-ads'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperacoesRoute = AuthenticatedOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedAjustesIndexRoute =
  AuthenticatedAjustesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedAjustesPlanosRoute =
  AuthenticatedAjustesPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedAjustesPerfilRoute =
  AuthenticatedAjustesPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedAjustesOnboardingRoute =
  AuthenticatedAjustesOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedAjustesIntegracoesRoute =
  AuthenticatedAjustesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedAjustesEquipeRoute =
  AuthenticatedAjustesEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedAjustesComissaoRoute =
  AuthenticatedAjustesComissaoRouteImport.update({
    id: '/comissao',
    path: '/comissao',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const AuthenticatedAjustesCargosRoute =
  AuthenticatedAjustesCargosRouteImport.update({
    id: '/cargos',
    path: '/cargos',
    getParentRoute: () => AuthenticatedAjustesRoute,
  } as any)
const ApiPublicHooksSyncAdsRoute = ApiPublicHooksSyncAdsRouteImport.update({
  id: '/api/public/hooks/sync-ads',
  path: '/api/public/hooks/sync-ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ajustes': typeof AuthenticatedAjustesRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/ajustes/cargos': typeof AuthenticatedAjustesCargosRoute
  '/ajustes/comissao': typeof AuthenticatedAjustesComissaoRoute
  '/ajustes/equipe': typeof AuthenticatedAjustesEquipeRoute
  '/ajustes/integracoes': typeof AuthenticatedAjustesIntegracoesRoute
  '/ajustes/onboarding': typeof AuthenticatedAjustesOnboardingRoute
  '/ajustes/perfil': typeof AuthenticatedAjustesPerfilRoute
  '/ajustes/planos': typeof AuthenticatedAjustesPlanosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/ajustes/': typeof AuthenticatedAjustesIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/sync-ads': typeof ApiPublicHooksSyncAdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/ajustes/cargos': typeof AuthenticatedAjustesCargosRoute
  '/ajustes/comissao': typeof AuthenticatedAjustesComissaoRoute
  '/ajustes/equipe': typeof AuthenticatedAjustesEquipeRoute
  '/ajustes/integracoes': typeof AuthenticatedAjustesIntegracoesRoute
  '/ajustes/onboarding': typeof AuthenticatedAjustesOnboardingRoute
  '/ajustes/perfil': typeof AuthenticatedAjustesPerfilRoute
  '/ajustes/planos': typeof AuthenticatedAjustesPlanosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/ajustes': typeof AuthenticatedAjustesIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/sync-ads': typeof ApiPublicHooksSyncAdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/operacoes': typeof AuthenticatedOperacoesRoute
  '/_authenticated/ajustes/cargos': typeof AuthenticatedAjustesCargosRoute
  '/_authenticated/ajustes/comissao': typeof AuthenticatedAjustesComissaoRoute
  '/_authenticated/ajustes/equipe': typeof AuthenticatedAjustesEquipeRoute
  '/_authenticated/ajustes/integracoes': typeof AuthenticatedAjustesIntegracoesRoute
  '/_authenticated/ajustes/onboarding': typeof AuthenticatedAjustesOnboardingRoute
  '/_authenticated/ajustes/perfil': typeof AuthenticatedAjustesPerfilRoute
  '/_authenticated/ajustes/planos': typeof AuthenticatedAjustesPlanosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/ajustes/': typeof AuthenticatedAjustesIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/sync-ads': typeof ApiPublicHooksSyncAdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ajustes'
    | '/chat'
    | '/clientes'
    | '/equipe'
    | '/financeiro'
    | '/hoje'
    | '/operacoes'
    | '/ajustes/cargos'
    | '/ajustes/comissao'
    | '/ajustes/equipe'
    | '/ajustes/integracoes'
    | '/ajustes/onboarding'
    | '/ajustes/perfil'
    | '/ajustes/planos'
    | '/clientes/$id'
    | '/ajustes/'
    | '/clientes/'
    | '/api/public/hooks/sync-ads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/equipe'
    | '/financeiro'
    | '/hoje'
    | '/operacoes'
    | '/ajustes/cargos'
    | '/ajustes/comissao'
    | '/ajustes/equipe'
    | '/ajustes/integracoes'
    | '/ajustes/onboarding'
    | '/ajustes/perfil'
    | '/ajustes/planos'
    | '/clientes/$id'
    | '/ajustes'
    | '/clientes'
    | '/api/public/hooks/sync-ads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ajustes'
    | '/_authenticated/chat'
    | '/_authenticated/clientes'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/hoje'
    | '/_authenticated/operacoes'
    | '/_authenticated/ajustes/cargos'
    | '/_authenticated/ajustes/comissao'
    | '/_authenticated/ajustes/equipe'
    | '/_authenticated/ajustes/integracoes'
    | '/_authenticated/ajustes/onboarding'
    | '/_authenticated/ajustes/perfil'
    | '/_authenticated/ajustes/planos'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/ajustes/'
    | '/_authenticated/clientes/'
    | '/api/public/hooks/sync-ads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncAdsRoute: typeof ApiPublicHooksSyncAdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operacoes': {
      id: '/_authenticated/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AuthenticatedOperacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/ajustes/': {
      id: '/_authenticated/ajustes/'
      path: '/'
      fullPath: '/ajustes/'
      preLoaderRoute: typeof AuthenticatedAjustesIndexRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/ajustes/planos': {
      id: '/_authenticated/ajustes/planos'
      path: '/planos'
      fullPath: '/ajustes/planos'
      preLoaderRoute: typeof AuthenticatedAjustesPlanosRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/ajustes/perfil': {
      id: '/_authenticated/ajustes/perfil'
      path: '/perfil'
      fullPath: '/ajustes/perfil'
      preLoaderRoute: typeof AuthenticatedAjustesPerfilRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/ajustes/onboarding': {
      id: '/_authenticated/ajustes/onboarding'
      path: '/onboarding'
      fullPath: '/ajustes/onboarding'
      preLoaderRoute: typeof AuthenticatedAjustesOnboardingRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/ajustes/integracoes': {
      id: '/_authenticated/ajustes/integracoes'
      path: '/integracoes'
      fullPath: '/ajustes/integracoes'
      preLoaderRoute: typeof AuthenticatedAjustesIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/ajustes/equipe': {
      id: '/_authenticated/ajustes/equipe'
      path: '/equipe'
      fullPath: '/ajustes/equipe'
      preLoaderRoute: typeof AuthenticatedAjustesEquipeRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/ajustes/comissao': {
      id: '/_authenticated/ajustes/comissao'
      path: '/comissao'
      fullPath: '/ajustes/comissao'
      preLoaderRoute: typeof AuthenticatedAjustesComissaoRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/_authenticated/ajustes/cargos': {
      id: '/_authenticated/ajustes/cargos'
      path: '/cargos'
      fullPath: '/ajustes/cargos'
      preLoaderRoute: typeof AuthenticatedAjustesCargosRouteImport
      parentRoute: typeof AuthenticatedAjustesRoute
    }
    '/api/public/hooks/sync-ads': {
      id: '/api/public/hooks/sync-ads'
      path: '/api/public/hooks/sync-ads'
      fullPath: '/api/public/hooks/sync-ads'
      preLoaderRoute: typeof ApiPublicHooksSyncAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAjustesRouteChildren {
  AuthenticatedAjustesCargosRoute: typeof AuthenticatedAjustesCargosRoute
  AuthenticatedAjustesComissaoRoute: typeof AuthenticatedAjustesComissaoRoute
  AuthenticatedAjustesEquipeRoute: typeof AuthenticatedAjustesEquipeRoute
  AuthenticatedAjustesIntegracoesRoute: typeof AuthenticatedAjustesIntegracoesRoute
  AuthenticatedAjustesOnboardingRoute: typeof AuthenticatedAjustesOnboardingRoute
  AuthenticatedAjustesPerfilRoute: typeof AuthenticatedAjustesPerfilRoute
  AuthenticatedAjustesPlanosRoute: typeof AuthenticatedAjustesPlanosRoute
  AuthenticatedAjustesIndexRoute: typeof AuthenticatedAjustesIndexRoute
}

const AuthenticatedAjustesRouteChildren: AuthenticatedAjustesRouteChildren = {
  AuthenticatedAjustesCargosRoute: AuthenticatedAjustesCargosRoute,
  AuthenticatedAjustesComissaoRoute: AuthenticatedAjustesComissaoRoute,
  AuthenticatedAjustesEquipeRoute: AuthenticatedAjustesEquipeRoute,
  AuthenticatedAjustesIntegracoesRoute: AuthenticatedAjustesIntegracoesRoute,
  AuthenticatedAjustesOnboardingRoute: AuthenticatedAjustesOnboardingRoute,
  AuthenticatedAjustesPerfilRoute: AuthenticatedAjustesPerfilRoute,
  AuthenticatedAjustesPlanosRoute: AuthenticatedAjustesPlanosRoute,
  AuthenticatedAjustesIndexRoute: AuthenticatedAjustesIndexRoute,
}

const AuthenticatedAjustesRouteWithChildren =
  AuthenticatedAjustesRoute._addFileChildren(AuthenticatedAjustesRouteChildren)

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedOperacoesRoute: typeof AuthenticatedOperacoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedOperacoesRoute: AuthenticatedOperacoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncAdsRoute: ApiPublicHooksSyncAdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
